[benzinga]
api_key = "YOUR_BENZINGA_API_KEY"

[alpaca]
key = "YOUR_ALPACA_KEY"
secret = "YOUR_ALPACA_SECRET"

[email]
smtp_server = "smtp.example.com"
port = 587
sender_email = "your@email.com"
password = "your_password"
receiver_email = "receiver@email.com"

[telegram]
bot_token = "YOUR_BOT_TOKEN"
chat_id = "YOUR_CHAT_ID"
