# Fill these before deploy
BENZINGA_API_KEY = ""
ALPACA_API_KEY = ""
ALPACA_SECRET_KEY = ""
EMAIL_HOST = ""
EMAIL_PORT = 587
EMAIL_USERNAME = ""
EMAIL_PASSWORD = ""
TELEGRAM_BOT_TOKEN = ""
TELEGRAM_CHAT_ID = ""
